services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: stockManageDB
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin_ui
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - "8081:80"

  server:
    build: ./server
    container_name: node_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootPassword
      DB_NAME: stockManageDB
      JWT_SECRET: my_super_secret_jwt
    depends_on:
      - db

  # client:
    # build: ./frontend
    # container_name: react_ui
    # restart: always
    # ports:
      # - "5173:5173"
    # depends_on:
      # - server

volumes:
  db_data:
